# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/time/time.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16server/time/time.proto\x12\x04time\"\x17\n\tTimestamp\x12\n\n\x02ms\x18\x01 \x01(\x03\"#\n\x08\x44\x61tetime\x12\n\n\x02ms\x18\x01 \x01(\x05\x12\x0b\n\x03iso\x18\x02 \x01(\t28\n\x04Time\x12\x30\n\x0bGetDatetime\x12\x0f.time.Timestamp\x1a\x0e.time.Datetime\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.time.time_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TIMESTAMP']._serialized_start=32
  _globals['_TIMESTAMP']._serialized_end=55
  _globals['_DATETIME']._serialized_start=57
  _globals['_DATETIME']._serialized_end=92
  _globals['_TIME']._serialized_start=94
  _globals['_TIME']._serialized_end=150
# @@protoc_insertion_point(module_scope)
